name    'andschwa-mumble'
version '0.0.1'
source 'git://github.com/andschwa/puppet-mumble.git'
author 'Andrew Schwartzmeyer'
license 'MIT License'
summary 'Install and Manage a Mumble Server'
description 'Installs, configures, and manages a Mumble server (murmurd)'
project_page 'https://github.com/andschwa/puppet-mumble'

dependency 'puppetlabs/apt', '>= 1.4.0'
